version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://awesomeuser:awesomepassword@db:5432/mydatabase
    volumes:
      - .:/usr/src/app

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: awesomeuser
      POSTGRES_PASSWORD: awesomepassword
      POSTGRES_DB: mydatabase
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
